tap 'homebrew/cask-fonts'
cask 'font-noto-sans'
cask 'font-noto-serif'
cask 'font-noto-mono'
cask 'font-fira-mono'
cask 'font-roboto-mono'

cask 'kitty'
cask 'firefox'
cask 'visual-studio-code'
cask 'alfred'
cask 'vagrant-manager'

cask 'aws-vault'
cask 'minikube'
cask 'vagrant'
